### ISSUE TITLE
Incorrect meta link alternate

### ISSUE THREAD

**Issue by Rudd-O** [plone/plone.app.multilingual#206] opened 2016-01-19 23:56 UTC
Hi, with p.a.m installed, the <head> of my site contains this:

```
<link rel="alternate" href="http://127.0.1.1:8080/Rudd-O.com/es/ggregator" hreflang="es" /><link rel="alternate" href="http://127.0.1.1:8080/Rudd-O.com/en/egator" hreflang="en" />
```

(that is the raw non-proxy-passed content retrieved from the site in the same server)

Note that the link ought to be /es/aggregator and /en/aggregator.  There is something funky going on in how the alternate references are being processed.

**Comment by Rudd-O** [comment] 2016-01-19 23:57
I believe my site is using p.a.m 2.0.1.

**Comment by petschki** [comment] 2016-03-03 10:20
this is a duplicate of #153 isn't it?

**Comment by Rudd-O** [comment] 2016-03-03 23:09
Yep.  Mark it as a dupe.

**Comment by Gomez** [comment] 2016-05-13 10:40
Closed as dupe

**Closed by Gomez** 2016-05-13 10:40 UTC
