### ISSUE TITLE
bad alternate urls when serving with domain

### ISSUE THREAD

**Issue by simahawk** [plone/plone.app.multilingual#153] opened 2015-02-06 09:50 UTC
When I access a translated content view localhost:port the links are correct. 
For instance, viewing the page `http://localhost:8180/Plone/en/resources/resources-home` the output of `get_alternate_languages` is this:

```
[{'lang': 'ko', 'url': 'resources/resources-home'},
 {'lang': 'zh-cn', 'url': 'resources/resources-home'},
 {'lang': 'en', 'url': 'resources/resources-home'}, 
 {'lang': 'ja', 'url': 'resources/resources-home'}]
```

BUT if I access it from a domain (fake or not) like `www.mysite.test/en/resources/resources-home` the output is:

```
[{'lang': 'ko', 'url': 'rces/resources-home'},
 {'lang': 'zh-cn', 'url': 'rces/resources-home'}, 
 {'lang': 'en', 'url': 'rces/resources-home'}, 
 {'lang': 'ja', 'url': 'rces/resources-home'}]
```

This happens because the method removes the portal path from the url

https://github.com/plone/plone.app.multilingual/blob/master/src/plone/app/multilingual/browser/viewlets.py#L131

that is fine when serving on localhost but when you are serving from domain, the relative url is just fine.

I'd change the method like this:

```
[...]
portal_path = '/'.join(self.portal_state.portal().getPhysicalPath())
portal_path_len = len(portal_path)
alternates = []
for item in results:
    url = item.getURL(relative=1)
    path_len = len('{0:s}/'.format(item.Language))
    if url.startswith(portal_path):
        path_len += portal_path_len
    url = url[path_len:]
[...]
```

Is that ok?

**Comment by simahawk** [comment] 2015-02-11 09:49
Here's the commit that fix this https://github.com/plone/plone.app.multilingual/commit/60a9594396a24442d2cdb5420e97adde7223d44d
I ran the alternate test and it's still passing but I'd like to specifically test the case of a "real" virtualhost.
Does anybody know how to fake it properly in tests?

**Comment by simahawk** [comment] 2015-03-13 12:40
@bloodbare @datakurre can you give me some pointers for adding tests on this? I really want to fix it and get it merged :)

**Comment by datakurre** [comment] 2015-03-13 12:50
@simahawk Create test requests with VHM urls like 

    http://nohost/VirtualHostBase/http/nohost:80/plone/VirtualHostRoot/_vh_subplone

**Comment by datakurre** [comment] 2015-04-07 10:21
@simahawk Could you post / push your broken test with VHM URLs?

**Comment by sneridagh** [comment] 2015-05-25 10:18
@simahawk @datakurre Any developments on this? I have the same issue, ZODB with mount points does not work either.

**Comment by sneridagh** [comment] 2015-05-25 10:28
@simahawk @datakurre What takes me to the point... why aren't we using a plain absolute_url here for the URLs? There is a special reason that I'm missing?

**Comment by datakurre** [comment] 2015-05-25 10:55
@sneridagh Maybe @bloodbare knows? :)

**Comment by simahawk** [comment] 2015-05-25 13:44
@sneridagh ohhh... finally someone w/ the same issue :)

The reason for that is explained in docstring:

```
"""       Cache relative urls only. If we have multilingual sites
           and multi domain site caching absolute urls will result in
           very inefficient caching. Build absolute url in template.
"""
```

My fix IS working, I'm using it in production (overriden the viewlet from one of my packages).
The only problem for me was: testing it.
@sneridagh try that, if it works for you, let's merge my fix, update the changelog and do a release, because this is a major bug for indexing too.

**Comment by simahawk** [comment] 2015-05-25 13:47
@sneridagh also, I'd say that that caching is still inefficient because it gets invalidate whenever the catalog counter is updated... which can occur a loooooooooot of times, totally unrelated to the translations themselves. But this is another story :)

**Comment by datakurre** [comment] 2015-05-25 13:55
@simahawk I looked into testing that at Sorrento and you were correct that it's not possible in integration test, because of the test request :( It really looked like the easiest way would be functional test and zope.testbrowser.

**Comment by sneridagh** [comment] 2015-05-25 15:57
I've finally found the LinguaPlone code where @bloodbare and I fixed a similar issue five years ago! Maybe this can help. You can find it in:

https://github.com/plone/Products.LinguaPlone/blob/master/Products/LinguaPlone/tests/test_selector.py

test_languages_vhr test.

**Comment by bloodbare** [comment] 2015-05-26 10:28
Hey, sorry I missed this issue, if we can test with with the virtual host will be great ! @sneridagh can help , he wrote that tests and commented out the test on pam for virtualhost :) https://github.com/plone/plone.app.multilingual/blob/master/src/plone/app/multilingual/tests/test_selector.py#L683

**Comment by datakurre** [comment] 2015-05-26 10:42
@bloodbare @sneridagh You just got me confirmed that functional test browser testing is the only sane way to do VHR/M tests :)

**Comment by bloodbare** [comment] 2015-05-26 10:44
@datakurre yes ! if you never find a better way would be great , but VHR is a /&·"%/$"!!

**Comment by petschki** [comment] 2016-03-03 10:26
got bitten by this also ... @simahawk why not use `item.getPath()` instead of `item.getURL(relative=1)` ? getPath() is always the same regardless of virtualhosting or not ...

**Comment by Rudd-O** [comment] 2016-05-14 01:39
Still not fixed after years?

**Comment by thet** [comment] 2016-05-14 23:59
Repo, which claims to fix this: https://github.com/collective/collective.pamfixes

@zcashero why not fixing it in p.a.m itself?

**Comment by zcashero** [comment] 2016-05-16 17:09
This is mainly intended as a quick patch so that we can immediately update our products (which still use p.a.m 1.x), and the next step will be to fix it directly in p.a.m with a PR.

However, as hinted above, will probably need some help developing the tests that are able to duplicate the situation where this bug appears.

**Comment by erral** [comment] 2017-05-17 07:37
I think that the `getPath(relative=1)` and `getPath()` approach can be simply exchanged by `getURL()` and a small change in the template and tests.

It is the simplest solution that will work in any scenario, because `getURL()` works in any scenario.

The getPath() and caching stuff looks like premature optimization to me, in LinguaPlone the language alternate viewlet simply calls `absolute_url` for each translation:

https://github.com/plone/Products.LinguaPlone/blob/master/Products/LinguaPlone/browser/contentlinkviewlet.py

**Comment by erral** [comment] 2017-05-17 08:00
I prepared pull-requests for all PAM versions:

https://github.com/plone/plone.app.multilingual/pull/270
https://github.com/plone/plone.app.multilingual/pull/271
https://github.com/plone/plone.app.multilingual/pull/272
https://github.com/plone/plone.app.multilingual/pull/273

**Comment by erral** [comment] 2017-05-17 08:30
The pull requests pass. Can someone review them please?

**Comment by erral** [comment] 2017-06-01 06:22
@jensens merged the fixes thanks!

We can close this.

**Closed by erral** 2017-06-01 06:22 UTC
Labels: 01 type: bug
